id: 7c5935a26b674d0bb7153fc3dfdd9ec5
initial_creation_type: ocr
source_metadata:
  volumes:
    1b094e34fa934c42aa5d4c23a1c9ed78:
      base_file: v096.txt
      image_group_id: I1PD95942
      title: དམིགས་པ་བརྟག་པ།
      total_pages: 1198
      volume_number: 97
